name: FTP Deploy

on:
  push:
    branches:
      - main # Der Workflow startet, sobald du etwas in den "main" Branch pushst

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # server-dir: ./httpdocs/  # Optional: Zielordner auf deinem Server
